<?php

use Illuminate\Database\Seeder;

class HocBong extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('hocbong')->delete();
        DB::table('hocbong')->insert(['id_NguoiDang' => 1, 'NgayTao' => "2018-11-01 00:00:00", 'AnhBia' => "css/pictures/mainbackground.png", 'TenHocBong' => "Học bổng Quốc tế của Đại học Edith Cowan tại Úc, năm 2019", 'id_LoaiHb' => 1, 'deadline' => "2018-11-08", 'id_TruongHoc' => 1, 'id_BacHoc' => 1, 'id_NganhHoc' => 8, 'id_GiaTriHb' => 0, 'SoLuong' => 50, 'YeuCau' => "Các quốc gia đủ điều kiện:  Ứng viên quốc tế đủ điều kiện đăng ký học bổng này.\nYêu cầu đầu vào:  Để đủ điều kiện nhận học bổng này, bạn phải:\n- Đạt được thành tích học tập cao.\n- Bắt đầu học tại ECU vào năm 2019 hoặc 2020.\n- Đáp ứng các yêu cầu nhập học của khóa học bạn chọn.\n- Không được nhận học bổng của chính phủ hoặc tài trợ công nghiệp.\nYêu cầu tiếng Anh:  Ứng viên quốc tế phải đáp ứng các yêu cầu về ngôn ngữ do trường đề ra.", 'ThuTucNop' => "Cách nộp đơn: Ứng viên nộp đơn theo học tại trường sẽ tự động được xét học bổng, không cần nộp đơn.", 'LinkDangKy' => "", 'NguonThongTin' => "", 'SoLuotQuanTam' => 120, 'id_TrangThaiHb' => 1]);
        DB::table('hocbong')->insert(['id_NguoiDang' => 1, 'NgayTao' => "2018-12-21 00:00:00", 'AnhBia' => "css/pictures/mainbackground.png", 'TenHocBong' => "Học bổng Lidcombe Catholic Club bậc Đại học và sau đại học tại Úc, 2019", 'id_LoaiHb' => 1, 'deadline' => "2018-11-08", 'id_TruongHoc' => 1, 'id_BacHoc' => 1, 'id_NganhHoc' => 1, 'id_GiaTriHb' => 0, 'SoLuong' => 100, 'YeuCau' => "Các quốc gia đủ điều kiện:  Ứng viên quốc tế đủ điều kiện đăng ký học bổng này.\nYêu cầu đầu vào:  Để đủ điều kiện nhận học bổng này, bạn phải:\n- Đạt được thành tích học tập cao.\n- Bắt đầu học tại ECU vào năm 2019 hoặc 2020.\n- Đáp ứng các yêu cầu nhập học của khóa học bạn chọn.\n- Không được nhận học bổng của chính phủ hoặc tài trợ công nghiệp.\nYêu cầu tiếng Anh:  Ứng viên quốc tế phải đáp ứng các yêu cầu về ngôn ngữ do trường đề ra.", 'ThuTucNop' => "Cách nộp đơn: Ứng viên nộp đơn theo học tại trường sẽ tự động được xét học bổng, không cần nộp đơn.", 'LinkDangKy' => "", 'NguonThongTin' => "", 'SoLuotQuanTam' => 2450, 'id_TrangThaiHb' => 1]);
        DB::table('hocbong')->insert(['id_NguoiDang' => 1, 'NgayTao' => "2018-11-11 00:00:00", 'AnhBia' => "css/pictures/mainbackground.png", 'TenHocBong' => "Học bổng nhập học của Đại học Otago tại New Zealand, 2019", 'id_LoaiHb' => 2, 'deadline' => "2019-11-18", 'id_TruongHoc' => 1, 'id_BacHoc' => 1, 'id_NganhHoc' => 4, 'id_GiaTriHb' => 0, 'SoLuong' => 10, 'YeuCau' => "Các quốc gia đủ điều kiện:  Ứng viên quốc tế đủ điều kiện đăng ký học bổng này.\nYêu cầu đầu vào:  Để đủ điều kiện nhận học bổng này, bạn phải:\n- Đạt được thành tích học tập cao.\n- Bắt đầu học tại ECU vào năm 2019 hoặc 2020.\n- Đáp ứng các yêu cầu nhập học của khóa học bạn chọn.\n- Không được nhận học bổng của chính phủ hoặc tài trợ công nghiệp.\nYêu cầu tiếng Anh:  Ứng viên quốc tế phải đáp ứng các yêu cầu về ngôn ngữ do trường đề ra.", 'ThuTucNop' => "Cách nộp đơn: Ứng viên nộp đơn theo học tại trường sẽ tự động được xét học bổng, không cần nộp đơn.", 'LinkDangKy' => "", 'NguonThongTin' => "", 'SoLuotQuanTam' => 2450, 'id_TrangThaiHb' => 1]);
        DB::table('hocbong')->insert(['id_NguoiDang' => 1, 'NgayTao' => "2018-10-05 00:00:00", 'AnhBia' => "css/pictures/mainbackground.png", 'TenHocBong' => "Học bổng Quốc tế của Đại học Edith Cowan tại Úc, năm 2019", 'id_LoaiHb' => 1, 'deadline' => "2018-11-28", 'id_TruongHoc' => 1, 'id_BacHoc' => 2, 'id_NganhHoc' => 1, 'id_GiaTriHb' => 0, 'SoLuong' => 20, 'YeuCau' => "Các quốc gia đủ điều kiện:  Ứng viên quốc tế đủ điều kiện đăng ký học bổng này.\nYêu cầu đầu vào:  Để đủ điều kiện nhận học bổng này, bạn phải:\n- Đạt được thành tích học tập cao.\n- Bắt đầu học tại ECU vào năm 2019 hoặc 2020.\n- Đáp ứng các yêu cầu nhập học của khóa học bạn chọn.\n- Không được nhận học bổng của chính phủ hoặc tài trợ công nghiệp.\nYêu cầu tiếng Anh:  Ứng viên quốc tế phải đáp ứng các yêu cầu về ngôn ngữ do trường đề ra.", 'ThuTucNop' => "Cách nộp đơn: Ứng viên nộp đơn theo học tại trường sẽ tự động được xét học bổng, không cần nộp đơn.", 'LinkDangKy' => "", 'NguonThongTin' => "", 'SoLuotQuanTam' => 2450, 'id_TrangThaiHb' => 1]);
        DB::table('hocbong')->insert(['id_NguoiDang' => 1, 'NgayTao' => "2018-09-11 00:00:00", 'AnhBia' => "css/pictures/mainbackground.png", 'TenHocBong' => "Chương trình Học bổng Tiến sĩ Quốc tế của Đại học Basel ở Thụy Sĩ, năm 2019", 'id_LoaiHb' => 3, 'deadline' => "2018-12-08", 'id_TruongHoc' => 2, 'id_BacHoc' => 1, 'id_NganhHoc' => 5, 'id_GiaTriHb' => 0, 'SoLuong' => 0, 'YeuCau' => "Các quốc gia đủ điều kiện:  Ứng viên quốc tế đủ điều kiện đăng ký học bổng này.\nYêu cầu đầu vào:  Để đủ điều kiện nhận học bổng này, bạn phải:\n- Đạt được thành tích học tập cao.\n- Bắt đầu học tại ECU vào năm 2019 hoặc 2020.\n- Đáp ứng các yêu cầu nhập học của khóa học bạn chọn.\n- Không được nhận học bổng của chính phủ hoặc tài trợ công nghiệp.\nYêu cầu tiếng Anh:  Ứng viên quốc tế phải đáp ứng các yêu cầu về ngôn ngữ do trường đề ra.", 'ThuTucNop' => "Cách nộp đơn: Ứng viên nộp đơn theo học tại trường sẽ tự động được xét học bổng, không cần nộp đơn.", 'LinkDangKy' => "", 'NguonThongTin' => "", 'SoLuotQuanTam' => 2450, 'id_TrangThaiHb' => 1]);
        
    }
}
