<?php

use Illuminate\Database\Seeder;

class QuocGia extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('quocgia')->delete();
        DB::table('quocgia')->insert(['TenQuocGia' => "Afghanistan", 'AnhQuocKy' => "pic/flags/flag-of-Afghanistan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Albania", 'AnhQuocKy' => "pic/flags/flag-of-Albania.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Algeria", 'AnhQuocKy' => "pic/flags/flag-of-Algeria.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "American Samoa", 'AnhQuocKy' => "pic/flags/flag-of-American-Samoa.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Andorra", 'AnhQuocKy' => "pic/flags/flag-of-Andorra.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Angola", 'AnhQuocKy' => "pic/flags/flag-of-Angola.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Anguilla", 'AnhQuocKy' => "pic/flags/flag-of-Anguilla.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Antarctica", 'AnhQuocKy' => "pic/flags/flag-of-Antarctica.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Antigua And Barbuda", 'AnhQuocKy' => "pic/flags/flag-of-Antigua-And-Barbuda.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Argentina", 'AnhQuocKy' => "pic/flags/flag-of-Argentina.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Armenia", 'AnhQuocKy' => "pic/flags/flag-of-Armenia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Aruba", 'AnhQuocKy' => "pic/flags/flag-of-Aruba.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Australia", 'AnhQuocKy' => "pic/flags/flag-of-Australia.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Austria", 'AnhQuocKy' => "pic/flags/flag-of-Austria.jpg",'id_KhuVuc' => 4]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Azerbaijan", 'AnhQuocKy' => "pic/flags/flag-of-Azerbaijan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bahamas The", 'AnhQuocKy' => "pic/flags/flag-of-Bahamas-The.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bahrain", 'AnhQuocKy' => "pic/flags/flag-of-Bahrain.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bangladesh", 'AnhQuocKy' => "pic/flags/flag-of-Bangladesh.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Barbados", 'AnhQuocKy' => "pic/flags/flag-of-Barbados.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Belarus", 'AnhQuocKy' => "pic/flags/flag-of-Belarus.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Belgium", 'AnhQuocKy' => "pic/flags/flag-of-Belgium.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Belize", 'AnhQuocKy' => "pic/flags/flag-of-Belize.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Benin", 'AnhQuocKy' => "pic/flags/flag-of-Benin.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bermuda", 'AnhQuocKy' => "pic/flags/flag-of-Bermuda.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bhutan", 'AnhQuocKy' => "pic/flags/flag-of-Bhutan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bolivia", 'AnhQuocKy' => "pic/flags/flag-of-Bolivia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bosnia and Herzegovina", 'AnhQuocKy' => "pic/flags/flag-of-Bosnia-and-Herzegovina.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Botswana", 'AnhQuocKy' => "pic/flags/flag-of-Botswana.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bouvet Island", 'AnhQuocKy' => "pic/flags/flag-of-Bouvet-Island.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Brazil", 'AnhQuocKy' => "pic/flags/flag-of-Brazil.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "British Indian Ocean Territory", 'AnhQuocKy' => "pic/flags/flag-of-British-Indian-Ocean-Territory.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Brunei", 'AnhQuocKy' => "pic/flags/flag-of-Brunei.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Bulgaria", 'AnhQuocKy' => "pic/flags/flag-of-Bulgaria.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Burkina Faso", 'AnhQuocKy' => "pic/flags/flag-of-Burkina-Faso.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Burundi", 'AnhQuocKy' => "pic/flags/flag-of-Burundi.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cambodia", 'AnhQuocKy' => "pic/flags/flag-of-Cambodia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cameroon", 'AnhQuocKy' => "pic/flags/flag-of-Cameroon.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Canada", 'AnhQuocKy' => "pic/flags/flag-of-Canada.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cape Verde", 'AnhQuocKy' => "pic/flags/flag-of-Cape-Verde.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cayman Islands", 'AnhQuocKy' => "pic/flags/flag-of-Cayman-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Central African Republic", 'AnhQuocKy' => "pic/flags/flag-of-Central-African-Republic.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Chad", 'AnhQuocKy' => "pic/flags/flag-of-Chad.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Chile", 'AnhQuocKy' => "pic/flags/flag-of-Chile.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "China", 'AnhQuocKy' => "pic/flags/flag-of-China.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Christmas Island", 'AnhQuocKy' => "pic/flags/flag-of-Christmas-Island.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cocos (Keeling) Islands", 'AnhQuocKy' => "pic/flags/flag-of-Cocos-(Keeling)-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Colombia", 'AnhQuocKy' => "pic/flags/flag-of-Colombia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Comoros", 'AnhQuocKy' => "pic/flags/flag-of-Comoros.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Republic Of The Congo", 'AnhQuocKy' => "pic/flags/flag-of-Republic-Of-The-Congo.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Democratic Republic Of The Congo", 'AnhQuocKy' => "pic/flags/flag-of-Democratic-Republic-Of-The-Congo.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cook Islands", 'AnhQuocKy' => "pic/flags/flag-of-Cook-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Costa Rica", 'AnhQuocKy' => "pic/flags/flag-of-Costa-Rica.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cote D''Ivoire (Ivory Coast)", 'AnhQuocKy' => "pic/flags/flag-of-Cote-D''Ivoire-(Ivory-Coast).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Croatia (Hrvatska)", 'AnhQuocKy' => "pic/flags/flag-of-Croatia-(Hrvatska).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cuba", 'AnhQuocKy' => "pic/flags/flag-of-Cuba.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Cyprus", 'AnhQuocKy' => "pic/flags/flag-of-Cyprus.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Czech Republic", 'AnhQuocKy' => "pic/flags/flag-of-Czech-Republic.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Denmark", 'AnhQuocKy' => "pic/flags/flag-of-Denmark.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Djibouti", 'AnhQuocKy' => "pic/flags/flag-of-Djibouti.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Dominica", 'AnhQuocKy' => "pic/flags/flag-of-Dominica.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Dominican Republic", 'AnhQuocKy' => "pic/flags/flag-of-Dominican-Republic.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "East Timor", 'AnhQuocKy' => "pic/flags/flag-of-East-Timor.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Ecuador", 'AnhQuocKy' => "pic/flags/flag-of-Ecuador.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Egypt", 'AnhQuocKy' => "pic/flags/flag-of-Egypt.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "El Salvador", 'AnhQuocKy' => "pic/flags/flag-of-El-Salvador.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Equatorial Guinea", 'AnhQuocKy' => "pic/flags/flag-of-Equatorial-Guinea.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Eritrea", 'AnhQuocKy' => "pic/flags/flag-of-Eritrea.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Estonia", 'AnhQuocKy' => "pic/flags/flag-of-Estonia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Ethiopia", 'AnhQuocKy' => "pic/flags/flag-of-Ethiopia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "External Territories of Australia", 'AnhQuocKy' => "pic/flags/flag-of-External-Territories-of-Australia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Falkland Islands", 'AnhQuocKy' => "pic/flags/flag-of-Falkland-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Faroe Islands", 'AnhQuocKy' => "pic/flags/flag-of-Faroe-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Fiji Islands", 'AnhQuocKy' => "pic/flags/flag-of-Fiji-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Finland", 'AnhQuocKy' => "pic/flags/flag-of-Finland.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "France", 'AnhQuocKy' => "pic/flags/flag-of-France.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "French Guiana", 'AnhQuocKy' => "pic/flags/flag-of-French-Guiana.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "French Polynesia", 'AnhQuocKy' => "pic/flags/flag-of-French-Polynesia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "French Southern Territories", 'AnhQuocKy' => "pic/flags/flag-of-French-Southern-Territories.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Gabon", 'AnhQuocKy' => "pic/flags/flag-of-Gabon.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Gambia The", 'AnhQuocKy' => "pic/flags/flag-of-Gambia-The.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Georgia", 'AnhQuocKy' => "pic/flags/flag-of-Georgia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Germany", 'AnhQuocKy' => "pic/flags/flag-of-Germany.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Ghana", 'AnhQuocKy' => "pic/flags/flag-of-Ghana.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Gibraltar", 'AnhQuocKy' => "pic/flags/flag-of-Gibraltar.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Greece", 'AnhQuocKy' => "pic/flags/flag-of-Greece.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Greenland", 'AnhQuocKy' => "pic/flags/flag-of-Greenland.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Grenada", 'AnhQuocKy' => "pic/flags/flag-of-Grenada.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guadeloupe", 'AnhQuocKy' => "pic/flags/flag-of-Guadeloupe.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guam", 'AnhQuocKy' => "pic/flags/flag-of-Guam.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guatemala", 'AnhQuocKy' => "pic/flags/flag-of-Guatemala.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guernsey and Alderney", 'AnhQuocKy' => "pic/flags/flag-of-Guernsey-and-Alderney.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guinea", 'AnhQuocKy' => "pic/flags/flag-of-Guinea.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guinea-Bissau", 'AnhQuocKy' => "pic/flags/flag-of-Guinea-Bissau.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Guyana", 'AnhQuocKy' => "pic/flags/flag-of-Guyana.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Haiti", 'AnhQuocKy' => "pic/flags/flag-of-Haiti.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Heard and McDonald Islands", 'AnhQuocKy' => "pic/flags/flag-of-Heard-and-McDonald-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Honduras", 'AnhQuocKy' => "pic/flags/flag-of-Honduras.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Hong Kong S.A.R.", 'AnhQuocKy' => "pic/flags/flag-of-Hong-Kong-S.A.R..jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Hungary", 'AnhQuocKy' => "pic/flags/flag-of-Hungary.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Iceland", 'AnhQuocKy' => "pic/flags/flag-of-Iceland.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "India", 'AnhQuocKy' => "pic/flags/flag-of-India.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Indonesia", 'AnhQuocKy' => "pic/flags/flag-of-Indonesia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Iran", 'AnhQuocKy' => "pic/flags/flag-of-Iran.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Iraq", 'AnhQuocKy' => "pic/flags/flag-of-Iraq.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Ireland", 'AnhQuocKy' => "pic/flags/flag-of-Ireland.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Israel", 'AnhQuocKy' => "pic/flags/flag-of-Israel.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Italy", 'AnhQuocKy' => "pic/flags/flag-of-Italy.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Jamaica", 'AnhQuocKy' => "pic/flags/flag-of-Jamaica.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Japan", 'AnhQuocKy' => "pic/flags/flag-of-Japan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Jersey", 'AnhQuocKy' => "pic/flags/flag-of-Jersey.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Jordan", 'AnhQuocKy' => "pic/flags/flag-of-Jordan.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Kazakhstan", 'AnhQuocKy' => "pic/flags/flag-of-Kazakhstan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Kenya", 'AnhQuocKy' => "pic/flags/flag-of-Kenya.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Kiribati", 'AnhQuocKy' => "pic/flags/flag-of-Kiribati.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Korea North", 'AnhQuocKy' => "pic/flags/flag-of-Korea-North.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Korea South", 'AnhQuocKy' => "pic/flags/flag-of-Korea-South.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Kuwait", 'AnhQuocKy' => "pic/flags/flag-of-Kuwait.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Kyrgyzstan", 'AnhQuocKy' => "pic/flags/flag-of-Kyrgyzstan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Laos", 'AnhQuocKy' => "pic/flags/flag-of-Laos.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Latvia", 'AnhQuocKy' => "pic/flags/flag-of-Latvia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Lebanon", 'AnhQuocKy' => "pic/flags/flag-of-Lebanon.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Lesotho", 'AnhQuocKy' => "pic/flags/flag-of-Lesotho.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Liberia", 'AnhQuocKy' => "pic/flags/flag-of-Liberia.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Libya", 'AnhQuocKy' => "pic/flags/flag-of-Libya.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Liechtenstein", 'AnhQuocKy' => "pic/flags/flag-of-Liechtenstein.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Lithuania", 'AnhQuocKy' => "pic/flags/flag-of-Lithuania.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Luxembourg", 'AnhQuocKy' => "pic/flags/flag-of-Luxembourg.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Macau S.A.R.", 'AnhQuocKy' => "pic/flags/flag-of-Macau-S.A.R..jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Macedonia", 'AnhQuocKy' => "pic/flags/flag-of-Macedonia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Madagascar", 'AnhQuocKy' => "pic/flags/flag-of-Madagascar.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Malawi", 'AnhQuocKy' => "pic/flags/flag-of-Malawi.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Malaysia", 'AnhQuocKy' => "pic/flags/flag-of-Malaysia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Maldives", 'AnhQuocKy' => "pic/flags/flag-of-Maldives.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mali", 'AnhQuocKy' => "pic/flags/flag-of-Mali.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Malta", 'AnhQuocKy' => "pic/flags/flag-of-Malta.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Man (Isle of)", 'AnhQuocKy' => "pic/flags/flag-of-Man-(Isle-of).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Marshall Islands", 'AnhQuocKy' => "pic/flags/flag-of-Marshall-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Martinique", 'AnhQuocKy' => "pic/flags/flag-of-Martinique.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mauritania", 'AnhQuocKy' => "pic/flags/flag-of-Mauritania.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mauritius", 'AnhQuocKy' => "pic/flags/flag-of-Mauritius.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mayotte", 'AnhQuocKy' => "pic/flags/flag-of-Mayotte.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mexico", 'AnhQuocKy' => "pic/flags/flag-of-Mexico.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Micronesia", 'AnhQuocKy' => "pic/flags/flag-of-Micronesia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Moldova", 'AnhQuocKy' => "pic/flags/flag-of-Moldova.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Monaco", 'AnhQuocKy' => "pic/flags/flag-of-Monaco.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mongolia", 'AnhQuocKy' => "pic/flags/flag-of-Mongolia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Montserrat", 'AnhQuocKy' => "pic/flags/flag-of-Montserrat.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Morocco", 'AnhQuocKy' => "pic/flags/flag-of-Morocco.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Mozambique", 'AnhQuocKy' => "pic/flags/flag-of-Mozambique.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Myanmar", 'AnhQuocKy' => "pic/flags/flag-of-Myanmar.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Namibia", 'AnhQuocKy' => "pic/flags/flag-of-Namibia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Nauru", 'AnhQuocKy' => "pic/flags/flag-of-Nauru.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Nepal", 'AnhQuocKy' => "pic/flags/flag-of-Nepal.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Netherlands Antilles", 'AnhQuocKy' => "pic/flags/flag-of-Netherlands-Antilles.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Netherlands The", 'AnhQuocKy' => "pic/flags/flag-of-Netherlands-The.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "New Caledonia", 'AnhQuocKy' => "pic/flags/flag-of-New-Caledonia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "New Zealand", 'AnhQuocKy' => "pic/flags/flag-of-New-Zealand.jpg",'id_KhuVuc' => 4]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Nicaragua", 'AnhQuocKy' => "pic/flags/flag-of-Nicaragua.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Niger", 'AnhQuocKy' => "pic/flags/flag-of-Niger.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Nigeria", 'AnhQuocKy' => "pic/flags/flag-of-Nigeria.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Niue", 'AnhQuocKy' => "pic/flags/flag-of-Niue.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Norfolk Island", 'AnhQuocKy' => "pic/flags/flag-of-Norfolk-Island.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Northern Mariana Islands", 'AnhQuocKy' => "pic/flags/flag-of-Northern-Mariana-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Norway", 'AnhQuocKy' => "pic/flags/flag-of-Norway.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Oman", 'AnhQuocKy' => "pic/flags/flag-of-Oman.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Pakistan", 'AnhQuocKy' => "pic/flags/flag-of-Pakistan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Palau", 'AnhQuocKy' => "pic/flags/flag-of-Palau.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Palestinian Territory Occupied", 'AnhQuocKy' => "pic/flags/flag-of-Palestinian-Territory-Occupied.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Panama", 'AnhQuocKy' => "pic/flags/flag-of-Panama.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Papua new Guinea", 'AnhQuocKy' => "pic/flags/flag-of-Papua-new-Guinea.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Paraguay", 'AnhQuocKy' => "pic/flags/flag-of-Paraguay.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Peru", 'AnhQuocKy' => "pic/flags/flag-of-Peru.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Philippines", 'AnhQuocKy' => "pic/flags/flag-of-Philippines.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Pitcairn Island", 'AnhQuocKy' => "pic/flags/flag-of-Pitcairn-Island.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Poland", 'AnhQuocKy' => "pic/flags/flag-of-Poland.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Portugal", 'AnhQuocKy' => "pic/flags/flag-of-Portugal.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Puerto Rico", 'AnhQuocKy' => "pic/flags/flag-of-Puerto-Rico.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Qatar", 'AnhQuocKy' => "pic/flags/flag-of-Qatar.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Reunion", 'AnhQuocKy' => "pic/flags/flag-of-Reunion.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Romania", 'AnhQuocKy' => "pic/flags/flag-of-Romania.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Russia", 'AnhQuocKy' => "pic/flags/flag-of-Russia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Rwanda", 'AnhQuocKy' => "pic/flags/flag-of-Rwanda.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saint Helena", 'AnhQuocKy' => "pic/flags/flag-of-Saint-Helena.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saint Kitts And Nevis", 'AnhQuocKy' => "pic/flags/flag-of-Saint-Kitts-And-Nevis.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saint Lucia", 'AnhQuocKy' => "pic/flags/flag-of-Saint-Lucia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saint Pierre and Miquelon", 'AnhQuocKy' => "pic/flags/flag-of-Saint-Pierre-and-Miquelon.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saint Vincent And The Grenadines", 'AnhQuocKy' => "pic/flags/flag-of-Saint-Vincent-And-The-Grenadines.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Samoa", 'AnhQuocKy' => "pic/flags/flag-of-Samoa.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "San Marino", 'AnhQuocKy' => "pic/flags/flag-of-San-Marino.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Sao Tome and Principe", 'AnhQuocKy' => "pic/flags/flag-of-Sao-Tome-and-Principe.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Saudi Arabia", 'AnhQuocKy' => "pic/flags/flag-of-Saudi-Arabia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Senegal", 'AnhQuocKy' => "pic/flags/flag-of-Senegal.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Serbia", 'AnhQuocKy' => "pic/flags/flag-of-Serbia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Seychelles", 'AnhQuocKy' => "pic/flags/flag-of-Seychelles.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Sierra Leone", 'AnhQuocKy' => "pic/flags/flag-of-Sierra-Leone.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Singapore", 'AnhQuocKy' => "pic/flags/flag-of-Singapore.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Slovakia", 'AnhQuocKy' => "pic/flags/flag-of-Slovakia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Slovenia", 'AnhQuocKy' => "pic/flags/flag-of-Slovenia.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Smaller Territories of the UK", 'AnhQuocKy' => "pic/flags/flag-of-Smaller-Territories-of-the-UK.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Solomon Islands", 'AnhQuocKy' => "pic/flags/flag-of-Solomon-Islands.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Somalia", 'AnhQuocKy' => "pic/flags/flag-of-Somalia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "South Africa", 'AnhQuocKy' => "pic/flags/flag-of-South-Africa.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "South Georgia", 'AnhQuocKy' => "pic/flags/flag-of-South-Georgia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "South Sudan", 'AnhQuocKy' => "pic/flags/flag-of-South-Sudan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Spain", 'AnhQuocKy' => "pic/flags/flag-of-Spain.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Sri Lanka", 'AnhQuocKy' => "pic/flags/flag-of-Sri-Lanka.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Sudan", 'AnhQuocKy' => "pic/flags/flag-of-Sudan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Suriname", 'AnhQuocKy' => "pic/flags/flag-of-Suriname.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Svalbard And Jan Mayen Islands", 'AnhQuocKy' => "pic/flags/flag-of-Svalbard-And-Jan-Mayen-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Swaziland", 'AnhQuocKy' => "pic/flags/flag-of-Swaziland.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Sweden", 'AnhQuocKy' => "pic/flags/flag-of-Sweden.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Switzerland", 'AnhQuocKy' => "pic/flags/flag-of-Switzerland.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Syria", 'AnhQuocKy' => "pic/flags/flag-of-Syria.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Taiwan", 'AnhQuocKy' => "pic/flags/flag-of-Taiwan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tajikistan", 'AnhQuocKy' => "pic/flags/flag-of-Tajikistan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tanzania", 'AnhQuocKy' => "pic/flags/flag-of-Tanzania.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Thailand", 'AnhQuocKy' => "pic/flags/flag-of-Thailand.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Togo", 'AnhQuocKy' => "pic/flags/flag-of-Togo.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tokelau", 'AnhQuocKy' => "pic/flags/flag-of-Tokelau.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tonga", 'AnhQuocKy' => "pic/flags/flag-of-Tonga.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Trinidad And Tobago", 'AnhQuocKy' => "pic/flags/flag-of-Trinidad-And-Tobago.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tunisia", 'AnhQuocKy' => "pic/flags/flag-of-Tunisia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Turkey", 'AnhQuocKy' => "pic/flags/flag-of-Turkey.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Turkmenistan", 'AnhQuocKy' => "pic/flags/flag-of-Turkmenistan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Turks And Caicos Islands", 'AnhQuocKy' => "pic/flags/flag-of-Turks-And-Caicos-Islands.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Tuvalu", 'AnhQuocKy' => "pic/flags/flag-of-Tuvalu.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Uganda", 'AnhQuocKy' => "pic/flags/flag-of-Uganda.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Ukraine", 'AnhQuocKy' => "pic/flags/flag-of-Ukraine.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "United Arab Emirates", 'AnhQuocKy' => "pic/flags/flag-of-United-Arab-Emirates.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "United Kingdom", 'AnhQuocKy' => "pic/flags/flag-of-United-Kingdom.jpg",'id_KhuVuc' => 3]);
		DB::table('quocgia')->insert(['TenQuocGia' => "United States", 'AnhQuocKy' => "pic/flags/flag-of-United-States.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "United States Minor Outlying Islands", 'AnhQuocKy' => "pic/flags/flag-of-United-States-Minor-Outlying-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Uruguay", 'AnhQuocKy' => "pic/flags/flag-of-Uruguay.jpg",'id_KhuVuc' => 2]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Uzbekistan", 'AnhQuocKy' => "pic/flags/flag-of-Uzbekistan.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Vanuatu", 'AnhQuocKy' => "pic/flags/flag-of-Vanuatu.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Vatican City State (Holy See)", 'AnhQuocKy' => "pic/flags/flag-of-Vatican-City-State-(Holy-See).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Venezuela", 'AnhQuocKy' => "pic/flags/flag-of-Venezuela.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Vietnam", 'AnhQuocKy' => "pic/flags/flag-of-Vietnam.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Virgin Islands (British)", 'AnhQuocKy' => "pic/flags/flag-of-Virgin-Islands-(British).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Virgin Islands (US)", 'AnhQuocKy' => "pic/flags/flag-of-Virgin-Islands-(US).jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Wallis And Futuna Islands", 'AnhQuocKy' => "pic/flags/flag-of-Wallis-And-Futuna-Islands.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Western Sahara", 'AnhQuocKy' => "pic/flags/flag-of-Western-Sahara.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Yemen", 'AnhQuocKy' => "pic/flags/flag-of-Yemen.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Yugoslavia", 'AnhQuocKy' => "pic/flags/flag-of-Yugoslavia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Zambia", 'AnhQuocKy' => "pic/flags/flag-of-Zambia.jpg",'id_KhuVuc' => 1]);
		DB::table('quocgia')->insert(['TenQuocGia' => "Zimbabwe", 'AnhQuocKy' => "pic/flags/flag-of-Zimbabwe.jpg",'id_KhuVuc' => 1]);
	
    }
}
